import React from 'react';
import Image from "next/image";
import foodImage from "@/app/assets/food_image.jpg";
import classes from "../../components/blogPosts/blog.module.css";
import {Metadata} from "next";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function Layout({children}: Readonly<{ children: React.ReactNode }>): React.JSX.Element {
    return (
        <div>
            <div className={classes.blogHeader}>
                <Image
                    src={foodImage}
                    alt={"image"}
                    className={classes.roundedImg}
                    priority={true}
                />
                <h1 >Blog Page</h1>
            </div>
            {children}
        </div>
    );
}

